name: fractional_indexing
description: Implemention of base62 fractional indexing, in dart.
version: 1.0.0
repository: https://github.com/Chronos-Planning-Technologies/dart-fractional-indexing

environment:
  sdk: '>=3.0.0-218.0.dev <4.0.0'

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
